### ISSUE TITLE
10x6x4벌식 지원

### ISSUE THREAD

**Issue by quiple** [exqt/pixel-font-maker#2]
안녕하세요! 혹시 8x4x4벌식 말고도 10x6x4벌식은 지원하실 생각이 없으신지 조심스레 한번 여쭤봐도 될까요. 😅

참고 링크: [https://wiki.kldp.org/wiki.php/%C1%B6%C7%D5%B1%DB%B2%C3](https://wiki.kldp.org/wiki.php/%C1%B6%C7%D5%B1%DB%B2%C3)

**Comment by exqt** [comment]
구현해보겠습니다!
혹시 참고할만한 10x6x4로 구현된 폰트가 있을까요?

**Comment by quiple** [comment]
잘 모르겠네요. 10x6x4벌식으로 폰트를 만들었다는 분들이 계신 것 같기는 한데..

그리고 자료를 찾아보다 알게 되었는데 윈도우 굴림체 비트맵 폰트 같은 경우는 32x15x11벌 정도면 비슷하게 구현할 수 있다는 것 같네요 ㄷㄷ

>초성 32벌 = [중성에 의해 8벌] x [종성에 의해 4벌]
>(종성 없는 경우) 중성구분 : [ㅏㅑㅓㅕㅣ]/[ㅐㅒㅔㅖ]/[ㅗㅛㅡ]/[ㅘㅚㅢ]/[ㅙ]/[ㅜㅠ]/[ㅝㅟ]/[ㅞ]
>(종성 있는 경우) 중성구분 : [ㅏㅑㅓㅕㅣ]/[ㅐㅒㅔㅖ]/[ㅗㅛ]/[ㅘㅚㅢ]/[ㅙ]/[ㅜㅠㅡ]/[ㅝㅟ]/[ㅞ]
>종성구분 : [없음]/[ㄱㄲㄳㄵㄶㄷㅁㅂㅄㅅㅆㅇㅈㅋㅍ]/[ㄴ]/[ㄹㄺㄻㄼㄽㄾㄿㅀㅊㅌㅎ]
>
>중성 15벌 = [초성에 의해 3벌] + [초성에 의해 4벌] x [종성에 의해 3벌]
>(종성 없는 경우) 초성구분 : [나머지]/[ㄱㅋ]/[ㅎ] # 이 부분은 확실치 않음
>(종성 있는 경우) 초성구분 : [나머지]/[ㄱㅋ]/[ㄹㅌ]/[ㅊㅎ]
>종성구분 : [ㄱㄲㄳㄵㄶㄷㅁㅂㅄㅅㅆㅇㅈㅋㅍ]/[ㄴ]/[ㄹㄺㄻㄼㄽㄾㄿㅀㅊㅌㅎ]
>
>종성 11벌 = [중성에 의해 3벌] + [중성에 의해 4벌] x [초성에 의해 2벌]
>(초성구분 없는) 중성구분 : [ㅏㅑㅣ]/[ㅐㅒㅔㅖ]/[ㅓㅕ]
>(초성구분 있는) 중성구분 : [ㅗㅛ]/[ㅘㅚㅝㅟㅢ]/[ㅙㅞ]/[ㅜㅠㅡ]
>초성구분 : [ㄱㄲㄴㄷㄸㅁㅂㅃㅅㅆㅇㅈㅉㅋㅍ]/[ㄹㅊㅌㅎ]

참고 링크: [https://sites.google.com/site/unbitfonts/composite](https://sites.google.com/site/unbitfonts/composite)

**Comment by quiple** [comment]
가변 10x4x4벌식이 수가 적은데도 종성 ㄴ이 올 때를 고려해서 중성을 변화시킨 게 인상적이네요.

항상 이게 불만이었거든요...

**Comment by exqt** [comment]
일단 말씀주신 10x6x4랑 10x{3,4}x4랑 구현해봤습니다
바로 main 브랜치에 올렸는데 제대로 구현한지는 몰겠네요.. 한번 확인 부탁드립니다

P.S.(?)
1. 32x15x11도 필요하신가요?
2. 며칠 전부터 군인이라 시간이 많이 없네요 ㅠㅠ 늦어도 이해해주심 감사하겠습니다

**Comment by quiple** [comment]
와 감사합니다ㅠㅠ
그리고 32x15x11은 아무래도 너무 많은 것 같긴 합니다 ㅋㅋ
