### ISSUE TITLE
BDF 형식으로 출력

### ISSUE THREAD

**Issue by quiple** [exqt/pixel-font-maker#3]
안녕하세요! 혹시 트루타입 폰트 말고 BDF 형식으로도 출력되게 할 수 있을까요? 😅

참고 링크: [https://en.wikipedia.org/wiki/Glyph_Bitmap_Distribution_Format](https://en.wikipedia.org/wiki/Glyph_Bitmap_Distribution_Format)

**Comment by exqt** [comment]
추가해보겠습니다!
(+ 어디에 쓰시는건지 여쭤봐도 될까요? )

**Comment by quiple** [comment]
개인적으로 BDF가 트루타입보다 비트맵 폰트를 씹고 뜯고 맛보기가 더 편해서 그렇습니다 ㅎ
그냥 텍스트로 되어 있는 파일이라서요

**Comment by exqt** [comment]
갈무리 bdf 보고 구현해서 main 브랜치에 올렸습니다
제가 이해하지 못한 부분은 임의로 아무거나 적어 넣었는데
수정이나 추가해야 할 부분이 있다면 알려주세요

**Comment by quiple** [comment]
감사합니다! 이상하다 싶은 거 있으면 말씀드릴게요
