### ISSUE TITLE
폰트 사이즈가 너무 클때 문제 발생

### ISSUE THREAD

**Issue by Crisp2013** [exqt/pixel-font-maker#5]
옛날 폰트 컨버팅에 이용하던중 다음과 같은 문제가 발생해서 issues에 올립니다.

1. 세로 크기가 16px(추정, 24px에서는 확실히 발생) 이상일 때 ttf변환 시도(ttf export 또는 preview 보기)시 프로그램이 뻗는 현상
2. 가로 32px 이상 폰트 지원 불가(Uint32Array 자료형 문제)
(추가)
3. 폰트사이즈랑 관련없는건데, WOFF2 내보내기가 안됩니다.

**Comment by exqt** [comment]
![캡처](https://github.com/exqt/pixel-font-maker/assets/8168124/eeba3382-a60d-4185-918d-49d7dae91e3e)

저는 1의 경우 잘 작동합니다. 사용하시는 브라우저와 작업하시는 폰트 프로젝트 파일을 주시면 제가 다시 확인해보겠습니다.

2는 32x32 이상의 픽셀 폰트가 필요하신건가요? 만들땐 보통 그렇게 큰 폰트는 없어서 32bit로 충분하다고 생각했습니다. 필요하시면 구현해보겠습니다.

3은 woff2 일 경우 wasm 파일이 필요한데 제가 경로를 잘못줬습니다. 수정했고 제 github 페이지에서는 정상 동작 확인했습니다.

**Comment by Crisp2013** [comment]
죄송합니다. 대충 쓱하고 확인한거라 문제상황을 잘못 확인했었습니다.

1. 세로 높이가 24pt 이상일때 문제가 발생합니다. 24x24까지는 정상 작동합니다.
폰트 높이가 24pt를 넘어가면 문제가 발생하는거 같은데, 툴 문제로 가끔 보이지는 않지만 24pt이상 영역에 찍히는 것 같네요.

2. 모니터 화면 출력용은 아니고, 도트프린터용으로 48x48폰트를 찼았었습니다. 이거 변환해볼려고 했는데 안되서 혹시나 해서 여쭤보았습니다. 반드시 필요한건 아닙니다.
![image](https://github.com/exqt/pixel-font-maker/assets/24960466/eb60f701-7992-4095-825d-7a348bfdb033)
3. 정상 작동 확인했습니다 감사합니다.

**Comment by exqt** [comment]
1은 일단 해결된거 같은데 또 이상있으시면 말씀해주세요

2는 불필요하신걸로 이해하겠습니다
